### ISSUE TITLE
Not able to install Presidio via KIND

### ISSUE THREAD

**Issue by aseemsethi** [microsoft/presidio#357]
I did a "git clone", ran ./prerequisites.sh, and finally ran ./run-with-kind.sh
Everything looks good, till this last step, where i get this error.

Error: render error in "presidio/templates/analyzer-deployment.yaml": template: presidio/templates/analyzer-deployment.yaml:29:30: executing "presidio/templates/analyzer-deployment.yaml" at <.Values.analyzer.container.resources.requests.memory>: nil pointer evaluating interface {}.memory

Regards,
Aseem

**Comment by akrock** [comment]
@aseemsethi I hit the same issue, it's fixed by PR #354

**Comment by aseemsethi** [comment]
Thanks. Removing the duplicate "resources", enabled the script to run to completion. 

After the script completed, the status shows 2 entities below crashing repeatedly.
[root@localhost ~]# kubectl get pod -n presidio
NAME                                                                                   READY   STATUS             RESTARTS   AGE
presidio-demo-presidio-analyzer-6cb775f5b8-v8fk9               0/1     CrashLoopBackOff   14         53m
presidio-demo-presidio-anonymizer-86689bdb7c-jbks7         1/1     Running            0          53m
presidio-demo-presidio-anonymizer-image-66ff58b47c-2vbjt   1/1     Running            0          53m
presidio-demo-presidio-api-66c8dcc885-hjsj6                         0/1     CrashLoopBackOff   19         53m
presidio-demo-presidio-ocr-8f8c9b9fc-vfh5m                           1/1     Running            0          53m
presidio-demo-presidio-recognizersstore-75c57d98b-xdgg7    1/1     Running            0          53m
presidio-demo-presidio-scheduler-85f746b5cf-plfr5                 1/1     Running            0          53m

**Comment by akrock** [comment]
I had the same issue w/ the `presidio-analyzer` and I addressed it in #356 

I did not have any issues w/ the `presidio-api` image, but I'm running in full kubernetes

**Comment by aseemsethi** [comment]
Thanks for the PR diffs, but even after adding the following line to app.py, i still see restarts
-    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

root@localhost deployment]# kubectl get pod -n presidio
NAME                                                       READY   STATUS             RESTARTS   AGE
presidio-demo-presidio-analyzer-6cb775f5b8-qksjj           0/1     CrashLoopBackOff   6          13m
presidio-demo-presidio-anonymizer-86689bdb7c-dw7dk         1/1     Running            0          13m
presidio-demo-presidio-anonymizer-image-66ff58b47c-8gkm9   1/1     Running            0          13m
presidio-demo-presidio-api-66c8dcc885-4z4ph                0/1     CrashLoopBackOff   6          13m
presidio-demo-presidio-ocr-8f8c9b9fc-lbhjp                 1/1     Running            0          13m
presidio-demo-presidio-recognizersstore-75c57d98b-mhp7d    1/1     Running            0          13m
presidio-demo-presidio-scheduler-85f746b5cf-r47gw          1/1     Running            0          13m

[root@localhost deployment]# kubectl describe pod presidio-demo-presidio-api-66c8dcc885-4z4ph  --namespace presidio
Events:
  Type     Reason     Age                   From                         Message
  ----     ------     ----                  ----                         -------
  Normal   Scheduled  10m                   default-scheduler            Successfully assigned presidio/presidio-demo-presidio-api-66c8dcc885-4z4ph to kind-control-plane
  Normal   Pulling    4m (x3 over 10m)      kubelet, kind-control-plane  Pulling image "mcr.microsoft.com/presidio-api:latest"
  Warning  Unhealthy  4m (x6 over 4m50s)    kubelet, kind-control-plane  Liveness probe failed: Get http://10.244.0.18:8080/healthz: dial tcp 10.244.0.18:8080: connect: connection refused
  Warning  Unhealthy  4m (x6 over 4m50s)    kubelet, kind-control-plane  Readiness probe failed: Get http://10.244.0.18:8080/healthz: dial tcp 10.244.0.18:8080: connect: connection refused
  Normal   Killing    4m (x2 over 4m30s)    kubelet, kind-control-plane  Container presidio failed liveness probe, will be restarted
  Normal   Pulled     3m54s (x3 over 5m1s)  kubelet, kind-control-plane  Successfully pulled image "mcr.microsoft.com/presidio-api:latest"
  Normal   Created    3m54s (x3 over 5m)    kubelet, kind-control-plane  Created container presidio
  Normal   Started    3m53s (x3 over 5m)    kubelet, kind-control-plane  Started container presidio

**Comment by aseemsethi** [comment]
The API pod is also crashing continuously. From the events command, i see that HEalthZ check is failing - 
Liveness probe failed: Get   http://10.244.0.17:8080/healthz: dial tcp 10.244.0.17:8080: 
Where does this IP address 10.244.0.17 come from ?

The other IPs in the cluster are as follows:
==> v1/Service
NAME                                     TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)   AGE
presidio-demo-presidio-analyzer          ClusterIP  10.96.122.223   <none>       3001/TCP  2s
presidio-demo-presidio-anonymizer        ClusterIP  10.98.106.140   <none>       3001/TCP  2s
presidio-demo-presidio-anonymizer-image  ClusterIP  10.111.148.123  <none>       3001/TCP  2s
presidio-demo-presidio-api               ClusterIP  10.104.29.150   <none>       8080/TCP  2s
presidio-demo-presidio-ocr               ClusterIP  10.101.165.205  <none>       3001/TCP  2s
presidio-demo-presidio-recognizersstore  ClusterIP  10.100.222.237  <none>       3004/TCP  1s
presidio-demo-presidio-scheduler         ClusterIP  10.98.219.62    <none>       3001/TCP  2s


=========
kubectl describe pod presidio-demo-presidio-api-66c8dcc885-xjbln --namespace presidio
Events:
  Type     Reason     Age                    From                         Message
  ----     ------     ----                   ----                         -------
  Normal   Scheduled  14m                    default-scheduler            Successfully assigned presidio/presidio-demo-presidio-api-66c8dcc885-xjbln to kind-control-plane
  Normal   Started    9m36s (x2 over 10m)    kubelet, kind-control-plane  Started container presidio
  Normal   Pulling    9m14s (x3 over 14m)    kubelet, kind-control-plane  Pulling image "mcr.microsoft.com/presidio-api:latest"
  Warning  Unhealthy  9m14s (x6 over 10m)    kubelet, kind-control-plane  Liveness probe failed: Get http://10.244.0.17:8080/healthz: dial tcp 10.244.0.17:8080: connect: connection refused
  Normal   Killing    9m14s (x2 over 9m44s)  kubelet, kind-control-plane  Container presidio failed liveness probe, will be restarted
  Normal   Pulled     9m7s (x3 over 10m)     kubelet, kind-control-plane  Successfully pulled image "mcr.microsoft.com/presidio-api:latest"
  Warning  Unhealthy  9m7s (x7 over 10m)     kubelet, kind-control-plane  Readiness probe failed: Get http://10.244.0.17:8080/healthz: dial tcp 10.244.0.17:8080: connect: connection refused
  Normal   Created    9m6s (x3 over 10m)     kubelet, kind-control-plane  Created container presidio
  Warning  BackOff    4m47s (x9 over 7m14s)  kubelet, kind-control-plane  Back-off restarting failed container

**Comment by omri374** [comment]
FYI, in version 2.0.0 we have new sample deployments into Kind and K8S:
https://microsoft.github.io/presidio/samples/deployments/k8s/

**Comment by navalev** [comment]
@aseemsethi We recently released the new version on presidio V2, whcih includes updates to the deployment samples https://github.com/microsoft/presidio/tree/main/docs/samples/deployments 
This issue will be closed. Feel free to re-open in case this is not resolved.
